### ISSUE TITLE
상단 검색 기능에 관하여

### ISSUE THREAD

**Issue by uuidcode** [kakao/kakao.github.io#11]
ADT가 궁금해서 우측 상단 검색을 이용했습니다.

1. 아래와 같이 다음으로 연결되는데 자체적으로 검색이 되면 좋을 것 같습니다.
http://search.daum.net/search?w=tot&q=ADT%20site%3Atech.kakao.com

2. 다음에서 검색된 첫번째 검색된 결과인 "ADT 활용 예제1: MySQL Shard 데이터 재분배"를 클릭하면
아래 페이지가 열리며 연결이 비공개로 설정되어 있지 않습니다 라는 오류페이지가 뜹니다.
https://tech.kakao.com/2016/07/01/adt-mysql-shard-rebalancing/

3. ADT와 같이 연재성 글을 묶어서 볼수 있으면 좋겠습니다.

4. 아래 페이지에서 adt 태킹을 클릭하며
http://tech.kakao.com/page/2/
아래 페이지가 열리며 404 Not Found가 뜹니다.
http://tech.kakao.com/tags/adt

**Comment by iolo** [comment]
현재 카카오 기술 블로그는 github pages & jekyll을 이용하고 있습니다. 그래서 태그를 수동으로 처리하다보니 많이 쓰이는 태그는 따로 처리하지 못한 경우가 많습니다. adt 태그를 따로 묶어서 보고 싶으시면 파일을 하나 추가하는 풀리케를 해주시면 될 듯~
https 인증서 문제는 확인해볼께요~
피드백 감사합니다...m(_ _)m

**Comment by uuidcode** [comment]
상단 검색이 다음 검색으로 되어 있는데 이것을 Simple-Jekyll-Search를 이용하여
내부검색으로 한번 만들어 봤습니다.

https://github.com/kakao/kakao.github.io/pull/12
