### ISSUE TITLE
facebook, kakaotalk 등을 통한 공유, 좋아요 등의 소셜기능 추가

### ISSUE THREAD

**Issue by rollin96** [kakao/kakao.github.io#2]
블로그는 피드백! 일텐데...
아직은 아무것도 안붙어 있군요 ㅠ.ㅠ
언젠간 되겠죠...

**Comment by iolo** [comment]
각 페이지(포스트) 상단에... 페북,트위터,구플 공유 링크가 있습니다만...
이거 말고 어떤 걸 말씀하시는건가요?

**Comment by elfinxx** [comment]
화면 상단에 붙어있어서 잘 안보이신게 아닐까 싶습니다.

글을 쭉 다 읽고 마지막 부분에서 "아 괜찮은 글이다 공유해야지" 라고 생각하는 사용자의 경우 공유 버튼이 없는 점에 당황할 수 있을 것 같습니다.
