### ISSUE TITLE
카카오폰트의 저작권에 대해 여쭤보고 싶습니다.

### ISSUE THREAD

**Issue by fm3647** [kakao/kakao.github.io#54]
기술블로그소스는 아파치 라이센스를 적용했는데
카카오폰트에 대한 저작권에 대해 궁금하여 질문 드립니다.

**Comment by violetblue** [comment]
카카오폰트는 카카오 브랜드 전용 서체 입니다.

**Comment by highca** [comment]
@violetblue 다른 용도로 사용해도 괜찮은가요?

**Comment by violetblue** [comment]
@highca 카카오폰트는 카카오 브랜드 전용 서체로 다른 용도로 사용하실 수 없습니다.
